name: Flask CI with Snyk Code Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: --Checkout code--
      uses: actions/checkout@v3

    - name: --Set up Python--
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: --Install pip dependencies (minimal to run snyk CLI only)--
      run: pip install --upgrade pip

    - name: --Run Snyk Code Scan (SAST only)--
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: code test  # SAST scan
        args: "--all-projects"
